language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
# whitelist
branches:
  only:
    - master
    - staging
    - production
install:
  - dotnet restore
script:  
  - dotnet test ./UnitTests
deploy:
  # deploy to staging
  - provider: elasticbeanstalk
    access_key_id: "Encrypted <staging-access-key-id>="
    secret_access_key:
     secure: "Encypted <staging-secret-access-key>="
    region: "us-east-1"  
    app: "staging-example-app-name"
    env: "staging-example-app-environment"
    bucket_name: "staging-the-target-S3-bucket"
    on:
      branch: staging
  # deploy to production
  - provider: elasticbeanstalk
    access_key_id: "Encrypted <access-production-key-id>="
    secret_access_key:
     secure: "Encypted <secret-production-access-key>="
    region: "us-east-1"  
    app: "production"
    env: "production"
    bucket_name: "the-target-production-S3-bucket"
    on:
      branch: production