language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
# whitelist
branches:
  only:
    - master
    - staging
    - production
install:
  - dotnet restore
script:
  - dotnet test ./UnitTests
before_deploy:
  - if [[ $TRAVIS_BRANCH == 'staging' ]]; then
    echo "Building for Staging...";
    export ASPNETCORE_ENVIRONMENT="Staging";
    fi
  - if [[ $TRAVIS_BRANCH == 'production' ]]; then
    echo "Building for Production...";
    export ASPNETCORE_ENVIRONMENT="Production";
    fi
  - dotnet publish -c Release -o ../release
deploy:
  # deploy to staging
  - provider: script
    script: dotnet ./deploy/FtpDeployer.dll staging ./release
    on:
      branch: staging
  # deploy to production
  - provider: script
    script: dotnet ./deploy/FtpDeployer.dll production ./release
    on:
      branch: production
