version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: dotnet build
  - branches:
      only:
        - staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      WEBSITE_PATH: staging
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    deploy-script:
      - cmd: dotnet run --project deploy/FtpDeployer.csproj ./release
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      WEBSITE_PATH: production
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    deploy-script:
      - cmd: dotnet run --project deploy/FtpDeployer.csproj ./release
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet restore
clone_depth: 1
test_script:
  - cmd: dotnet test ./UnitTests
