version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: dotnet build
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      WEBSITE_PATH: production
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    deploy_script:
      - cmd: dotnet run --project deploy/FtpDeployer.csproj ./release
  - branches:
      only:
        - staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      WEBSITE_PATH: staging
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    artifacts:
      - path: ./release
        name: Release
        type: WebDeployPackage
    deploy:
      provider: WebDeploy
      server: $(WEB_HOST)
      website: $(WEBSITE_PATH)
      username: $(WEB_DEPLOYER_USERNAME)
      password: $(WEB_DEPLOYER_PASSWORD)
      ntlm: false
      remove_files: true
      artifact: Release
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet restore
clone_depth: 1
test_script:
  - cmd: dotnet test ./UnitTests
